#--------------------------------------------
#' Remove extra spaces from Hugin .net file generated by SamIam.
#'
#' \code{remove.sam.tabs} Removes extra spaces from SamIam .net file.
#'
#' Remove the tabs put into a .net file saved from SamIam. The file is
#' re-written. The tabs make loadHuginNet in gRain choke.
#'
#' @param fpath The path to the .net file
#' @return Nothing. 
#'
#' @examples
#' Coming soon.
#'
#' \dontrun{
#'  remove.sam.tabs("path/to/file/blah.net")
#' }
#--------------------------------------------
remove.sam.tabs<-function(fpath){
  system(paste("expand -t2 ",fpath," > ",fpath,"_new",sep=""))
  system(paste("mv -f ",fpath,"_new"," ",fpath,sep=""))
}